import type { Difficulty, Recipe } from "./types";

/**
 * RECIPE CONTENT
 * The recipes themselves stay in German – that is how they are written in the
 * videos. Everything around them (UI, labels, shop) is English.
 *
 * A new recipe = a new object in this array. `slug` defines the URL: /recipes/<slug>
 * `linkedProductSlugs` points at lib/products.ts and produces the
 * "What I use for this" block on the detail page.
 */
export const recipes: Recipe[] = [
  {
    slug: "schoko-babka",
    title: "Schoko-Babka mit doppelter Füllung",
    category: "backen",
    excerpt:
      "Der Klassiker aus dem Video: weicher Hefezopf mit einer Schokofüllung, die beim Schneiden Schichten zeigt.",
    image: "https://placehold.co/800x600/D4517A/FFFFFF?text=Schoko-Babka",
    videoUrl: "",
    videoPlatform: "instagram",
    prepTimeMinutes: 150,
    difficulty: "anspruchsvoll",
    servings: 12,
    ingredients: [
      { amount: "500 g", name: "Weizenmehl Type 550" },
      { amount: "70 g", name: "Zucker" },
      { amount: "1 Pck.", name: "Trockenhefe (7 g)" },
      { amount: "240 ml", name: "lauwarme Milch" },
      { amount: "2", name: "Eier (Größe M)" },
      { amount: "120 g", name: "weiche Butter" },
      { amount: "1 TL", name: "Salz" },
      { amount: "200 g", name: "Zartbitterschokolade" },
      { amount: "100 g", name: "Butter für die Füllung" },
      { amount: "40 g", name: "Kakaopulver" },
      { amount: "80 g", name: "Puderzucker" },
      { amount: "100 ml", name: "Wasser + 100 g Zucker für den Sirup" },
    ],
    steps: [
      "Mehl, Zucker, Hefe und Salz mischen. Milch und Eier zugeben, 5 Minuten kneten, bis sich der Teig von der Schüssel löst.",
      "Weiche Butter in drei Portionen einkneten – jede Portion vollständig einarbeiten, bevor die nächste dazukommt. Weitere 8 Minuten kneten.",
      "Teig abgedeckt 1 Stunde gehen lassen, danach mindestens 1 Stunde in den Kühlschrank. Kalter Teig lässt sich deutlich besser ausrollen.",
      "Für die Füllung Schokolade und Butter schmelzen, Kakao und Puderzucker unterrühren. Kurz abkühlen lassen, bis die Masse streichfähig ist.",
      "Teig zu einem Rechteck von ca. 40 × 50 cm ausrollen, Füllung gleichmäßig verstreichen, von der langen Seite aufrollen.",
      "Rolle längs halbieren, die Hälften mit der Schnittfläche nach oben umeinander drehen und in eine gefettete Kastenform (30 cm) legen.",
      "Nochmals 45 Minuten gehen lassen. Ofen auf 180 °C Ober-/Unterhitze vorheizen.",
      "35–40 Minuten backen. Währenddessen Wasser und Zucker aufkochen.",
      "Babka direkt nach dem Backen großzügig mit dem heißen Sirup bestreichen und in der Form auskühlen lassen.",
    ],
    linkedProductSlugs: ["linen-apron", "baking-book-pdf"],
    tags: ["Hefeteig", "Schokolade"],
    publishedAt: "2026-07-21",
    popularity: 98,
  },
  {
    slug: "zimtschnecken-ueber-nacht",
    title: "Über-Nacht-Zimtschnecken",
    category: "backen",
    excerpt:
      "Abends vorbereiten, morgens nur noch backen. 20 Minuten Arbeit am Vorabend, frische Schnecken zum Frühstück.",
    image: "https://placehold.co/800x600/E4CFB2/3B2A20?text=Zimtschnecken",
    videoUrl: "",
    videoPlatform: "tiktok",
    prepTimeMinutes: 45,
    difficulty: "mittel",
    servings: 9,
    ingredients: [
      { amount: "450 g", name: "Weizenmehl Type 550" },
      { amount: "50 g", name: "Zucker" },
      { amount: "7 g", name: "Trockenhefe" },
      { amount: "1 TL", name: "Salz" },
      { amount: "250 ml", name: "lauwarme Milch" },
      { amount: "1", name: "Ei" },
      { amount: "60 g", name: "weiche Butter" },
      { amount: "100 g", name: "weiche Butter für die Füllung" },
      { amount: "120 g", name: "brauner Zucker" },
      { amount: "2 EL", name: "Zimt" },
      { amount: "100 g", name: "Frischkäse" },
      { amount: "80 g", name: "Puderzucker" },
    ],
    steps: [
      "Alle Teigzutaten außer der Butter 5 Minuten kneten, dann die weiche Butter einarbeiten und weitere 5 Minuten kneten.",
      "45 Minuten gehen lassen, bis sich das Volumen deutlich vergrößert hat.",
      "Teig zu einem Rechteck (30 × 40 cm) ausrollen. Weiche Butter daraufstreichen, brauner Zucker und Zimt darüber.",
      "Von der langen Seite aufrollen und in 9 gleich große Stücke schneiden – am saubersten mit einem Stück Zwirn statt mit dem Messer.",
      "Schnecken in eine gefettete Auflaufform setzen, abdecken und über Nacht in den Kühlschrank stellen.",
      "Am Morgen 45 Minuten bei Raumtemperatur akklimatisieren lassen, Ofen auf 180 °C vorheizen.",
      "25 Minuten backen, bis die Oberfläche goldbraun ist.",
      "Frischkäse und Puderzucker glatt rühren und auf die noch warmen Schnecken streichen.",
    ],
    linkedProductSlugs: ["linen-apron", "dough-scraper-set"],
    tags: ["Vorbereiten", "Frühstück"],
    publishedAt: "2026-07-14",
    popularity: 95,
  },
  {
    slug: "new-york-cheesecake",
    title: "New York Cheesecake ohne Risse",
    category: "backen",
    excerpt:
      "Cremig bis in die Mitte, glatte Oberfläche. Der Trick liegt im Wasserbad und im langsamen Auskühlen.",
    image: "https://placehold.co/800x600/FBE7EE/3B2A20?text=Cheesecake",
    videoUrl: "",
    videoPlatform: "youtube",
    prepTimeMinutes: 90,
    difficulty: "mittel",
    servings: 12,
    ingredients: [
      { amount: "200 g", name: "Butterkekse" },
      { amount: "90 g", name: "geschmolzene Butter" },
      { amount: "900 g", name: "Doppelrahm-Frischkäse, zimmerwarm" },
      { amount: "200 g", name: "Zucker" },
      { amount: "200 g", name: "saure Sahne" },
      { amount: "4", name: "Eier, zimmerwarm" },
      { amount: "1 EL", name: "Vanilleextrakt" },
      { amount: "1 EL", name: "Speisestärke" },
      { amount: "1 Prise", name: "Salz" },
    ],
    steps: [
      "Kekse fein zerbröseln, mit der Butter mischen und in einer 24-cm-Springform fest andrücken. 10 Minuten bei 180 °C vorbacken, auskühlen lassen.",
      "Form von außen doppelt in Alufolie wickeln, damit im Wasserbad nichts eindringt.",
      "Frischkäse mit Zucker auf niedrigster Stufe glatt rühren – nicht schaumig schlagen, sonst reißt der Kuchen später.",
      "Saure Sahne, Stärke, Vanille und Salz unterrühren. Eier einzeln zugeben, jeweils nur bis zum Verbinden rühren.",
      "Masse auf den Boden gießen, Form in ein tiefes Blech stellen und kochendes Wasser bis zur halben Höhe angießen.",
      "Bei 160 °C 60–70 Minuten backen. Die Mitte darf bei leichtem Rütteln noch wackeln.",
      "Ofen ausschalten, Tür einen Spalt öffnen und den Kuchen 1 Stunde darin stehen lassen.",
      "Mindestens 6 Stunden, besser über Nacht, kalt stellen.",
    ],
    linkedProductSlugs: ["baking-book-pdf", "linen-apron"],
    tags: ["Klassiker", "Kuchen"],
    publishedAt: "2026-06-30",
    popularity: 88,
  },
  {
    slug: "bananenbrot-saftig",
    title: "Saftiges Bananenbrot in einer Schüssel",
    category: "backen",
    excerpt:
      "Eine Schüssel, ein Löffel, zehn Minuten Arbeit. Das Rezept für zu braune Bananen.",
    image: "https://placehold.co/800x600/E4CFB2/3B2A20?text=Bananenbrot",
    videoUrl: "",
    videoPlatform: "tiktok",
    prepTimeMinutes: 70,
    difficulty: "einfach",
    servings: 10,
    ingredients: [
      { amount: "3", name: "sehr reife Bananen" },
      { amount: "120 g", name: "brauner Zucker" },
      { amount: "2", name: "Eier" },
      { amount: "100 ml", name: "neutrales Öl" },
      { amount: "100 g", name: "Naturjoghurt" },
      { amount: "250 g", name: "Weizenmehl" },
      { amount: "1 TL", name: "Natron" },
      { amount: "1 TL", name: "Zimt" },
      { amount: "1 Prise", name: "Salz" },
      { amount: "80 g", name: "Schokotropfen (optional)" },
    ],
    steps: [
      "Ofen auf 175 °C vorheizen, Kastenform (25 cm) mit Backpapier auslegen.",
      "Bananen in einer großen Schüssel mit der Gabel zerdrücken – ruhig ein paar Stücke lassen.",
      "Zucker, Eier, Öl und Joghurt zugeben und verrühren.",
      "Mehl, Natron, Zimt und Salz darübersieben und nur so lange rühren, bis kein Mehl mehr sichtbar ist.",
      "Schokotropfen unterheben, Teig in die Form füllen.",
      "50–55 Minuten backen. Stäbchenprobe: es darf feucht, aber nicht teigig sein.",
      "10 Minuten in der Form ruhen lassen, dann auf einem Gitter auskühlen.",
    ],
    linkedProductSlugs: ["baking-book-pdf", "dough-scraper-set"],
    tags: ["Schnell", "Resteverwertung"],
    publishedAt: "2026-06-16",
    popularity: 91,
  },
  {
    slug: "zitronen-blechkuchen",
    title: "Zitronen-Blechkuchen für die ganze Runde",
    category: "backen",
    excerpt:
      "Ein Blech, 20 Stücke, hält drei Tage saftig. Mein Standard, wenn Besuch kommt.",
    image: "https://placehold.co/800x600/FBE7EE/3B2A20?text=Zitronenkuchen",
    videoUrl: "",
    videoPlatform: "instagram",
    prepTimeMinutes: 55,
    difficulty: "einfach",
    servings: 20,
    ingredients: [
      { amount: "300 g", name: "weiche Butter" },
      { amount: "300 g", name: "Zucker" },
      { amount: "6", name: "Eier" },
      { amount: "400 g", name: "Weizenmehl" },
      { amount: "1 Pck.", name: "Backpulver" },
      { amount: "200 g", name: "Naturjoghurt" },
      { amount: "3", name: "Bio-Zitronen (Abrieb und Saft)" },
      { amount: "200 g", name: "Puderzucker für die Glasur" },
    ],
    steps: [
      "Ofen auf 180 °C vorheizen, ein Backblech mit Backpapier auslegen.",
      "Butter und Zucker 5 Minuten hell und luftig aufschlagen.",
      "Eier einzeln unterrühren, dann Zitronenabrieb und Joghurt zugeben.",
      "Mehl und Backpulver unterheben, Teig auf dem Blech glatt streichen.",
      "25–30 Minuten backen, bis die Oberfläche goldgelb ist.",
      "Kuchen mit einem Spieß mehrfach einstechen und die Hälfte des Zitronensafts darüber verteilen, solange er heiß ist.",
      "Restlichen Saft mit Puderzucker verrühren und den ausgekühlten Kuchen damit glasieren.",
    ],
    linkedProductSlugs: ["baking-book-pdf", "linen-apron"],
    tags: ["Blechkuchen", "Für Gäste"],
    publishedAt: "2026-05-28",
    popularity: 76,
  },
  {
    slug: "cremige-tomaten-pasta",
    title: "Cremige Tomaten-Pasta in 20 Minuten",
    category: "herzhaft",
    excerpt:
      "Eine Pfanne, Zutaten aus dem Vorrat, und die Sauce bindet allein über das Nudelwasser.",
    image: "https://placehold.co/800x600/4F7C4A/FFFFFF?text=Tomaten-Pasta",
    videoUrl: "",
    videoPlatform: "tiktok",
    prepTimeMinutes: 20,
    difficulty: "einfach",
    servings: 2,
    ingredients: [
      { amount: "250 g", name: "Pasta (Rigatoni oder Penne)" },
      { amount: "2 EL", name: "Olivenöl" },
      { amount: "2", name: "Knoblauchzehen" },
      { amount: "3 EL", name: "Tomatenmark" },
      { amount: "400 g", name: "stückige Tomaten" },
      { amount: "100 ml", name: "Sahne oder Hafercuisine" },
      { amount: "40 g", name: "Parmesan" },
      { amount: "1 TL", name: "getrockneter Oregano" },
      { name: "Salz, Pfeffer, 1 Prise Zucker" },
      { name: "frisches Basilikum" },
    ],
    steps: [
      "Pasta in reichlich Salzwasser kochen. Eine Tasse Nudelwasser aufheben – das ist die Bindung für die Sauce.",
      "Knoblauch fein hacken und im Olivenöl 30 Sekunden anschwitzen, nicht bräunen.",
      "Tomatenmark zugeben und 2 Minuten mitrösten, bis es dunkler wird. Dieser Schritt macht den Geschmack aus.",
      "Mit den stückigen Tomaten ablöschen, Oregano, Salz, Pfeffer und eine Prise Zucker zugeben, 8 Minuten köcheln lassen.",
      "Sahne und Parmesan einrühren.",
      "Pasta direkt aus dem Topf in die Pfanne geben, mit einem Schuss Nudelwasser 1 Minute schwenken, bis die Sauce glänzt.",
      "Mit Basilikum und weiterem Parmesan servieren.",
    ],
    linkedProductSlugs: ["weeknight-pdf", "linen-apron"],
    tags: ["Feierabend", "Vegetarisch"],
    publishedAt: "2026-07-27",
    popularity: 99,
  },
  {
    slug: "ofen-gnocchi-gemuese",
    title: "Ofen-Gnocchi mit Gemüse vom Blech",
    category: "herzhaft",
    excerpt:
      "Alles roh auf ein Blech, 25 Minuten in den Ofen, fertig. Die Gnocchi werden außen knusprig.",
    image: "https://placehold.co/800x600/E7F1E4/3B2A20?text=Ofen-Gnocchi",
    videoUrl: "",
    videoPlatform: "instagram",
    prepTimeMinutes: 35,
    difficulty: "einfach",
    servings: 3,
    ingredients: [
      { amount: "500 g", name: "Gnocchi aus dem Kühlregal" },
      { amount: "300 g", name: "Kirschtomaten" },
      { amount: "1", name: "Zucchini" },
      { amount: "1", name: "rote Paprika" },
      { amount: "1", name: "rote Zwiebel" },
      { amount: "3 EL", name: "Olivenöl" },
      { amount: "125 g", name: "Mozzarella" },
      { amount: "1 TL", name: "getrockneter Thymian" },
      { name: "Salz, Pfeffer" },
    ],
    steps: [
      "Ofen auf 220 °C Umluft vorheizen.",
      "Zucchini, Paprika und Zwiebel in mundgerechte Stücke schneiden.",
      "Gemüse, Tomaten und die rohen Gnocchi auf einem Blech mit Öl, Thymian, Salz und Pfeffer vermengen. Alles in einer Schicht verteilen – nicht stapeln, sonst dämpft es statt zu rösten.",
      "20 Minuten backen, einmal wenden.",
      "Mozzarella in Stücken darüber zupfen und weitere 5 Minuten backen.",
      "Direkt vom Blech servieren.",
    ],
    linkedProductSlugs: ["weeknight-pdf"],
    tags: ["Ein Blech", "Vegetarisch"],
    publishedAt: "2026-07-07",
    popularity: 84,
  },
  {
    slug: "haehnchen-teriyaki-bowl",
    title: "Hähnchen-Teriyaki-Bowl",
    category: "herzhaft",
    excerpt:
      "Sauce aus vier Zutaten, die man immer da hat. Meal-Prep-tauglich für drei Tage.",
    image: "https://placehold.co/800x600/4F7C4A/FFFFFF?text=Teriyaki-Bowl",
    videoUrl: "",
    videoPlatform: "youtube",
    prepTimeMinutes: 30,
    difficulty: "einfach",
    servings: 2,
    ingredients: [
      { amount: "400 g", name: "Hähnchenbrust" },
      { amount: "150 g", name: "Sushi- oder Jasminreis" },
      { amount: "4 EL", name: "Sojasauce" },
      { amount: "2 EL", name: "Honig" },
      { amount: "2 EL", name: "Reisessig" },
      { amount: "1 TL", name: "geriebener Ingwer" },
      { amount: "1", name: "Karotte" },
      { amount: "1/2", name: "Gurke" },
      { amount: "1 EL", name: "Sesam" },
      { amount: "2", name: "Frühlingszwiebeln" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Sojasauce, Honig, Reisessig und Ingwer verrühren – das ist die komplette Sauce.",
      "Hähnchenbrust in Streifen schneiden und in einer heißen Pfanne 5 Minuten scharf anbraten.",
      "Sauce angießen und 3–4 Minuten einkochen lassen, bis sie das Fleisch glasiert.",
      "Karotte und Gurke in feine Stifte schneiden.",
      "Reis in Schüsseln füllen, Hähnchen und Gemüse darauf anrichten, mit Sesam und Frühlingszwiebeln bestreuen.",
    ],
    linkedProductSlugs: ["weeknight-pdf"],
    tags: ["Meal Prep", "Bowl"],
    publishedAt: "2026-06-23",
    popularity: 82,
  },
  {
    slug: "linsen-dal-30-min",
    title: "Rote-Linsen-Dal in 30 Minuten",
    category: "herzhaft",
    excerpt:
      "Ein Topf, günstige Zutaten, wärmt durch. Schmeckt am zweiten Tag noch besser.",
    image: "https://placehold.co/800x600/E7F1E4/3B2A20?text=Linsen-Dal",
    videoUrl: "",
    videoPlatform: "tiktok",
    prepTimeMinutes: 30,
    difficulty: "einfach",
    servings: 4,
    ingredients: [
      { amount: "250 g", name: "rote Linsen" },
      { amount: "1", name: "Zwiebel" },
      { amount: "3", name: "Knoblauchzehen" },
      { amount: "1 Stück", name: "Ingwer (daumengroß)" },
      { amount: "2 TL", name: "Currypulver" },
      { amount: "1 TL", name: "Kreuzkümmel" },
      { amount: "1/2 TL", name: "Kurkuma" },
      { amount: "400 ml", name: "Kokosmilch" },
      { amount: "400 g", name: "stückige Tomaten" },
      { amount: "500 ml", name: "Gemüsebrühe" },
      { amount: "1", name: "Limette" },
      { name: "frischer Koriander" },
    ],
    steps: [
      "Zwiebel, Knoblauch und Ingwer fein hacken und in etwas Öl 3 Minuten anschwitzen.",
      "Gewürze zugeben und 1 Minute mitrösten, bis es deutlich riecht.",
      "Linsen, Tomaten, Kokosmilch und Brühe zugeben und aufkochen.",
      "20 Minuten bei mittlerer Hitze köcheln lassen, gelegentlich umrühren, damit nichts ansetzt.",
      "Mit Salz und Limettensaft abschmecken – die Säure am Schluss macht den Unterschied.",
      "Mit Koriander servieren, dazu Reis oder Fladenbrot.",
    ],
    linkedProductSlugs: ["weeknight-pdf"],
    tags: ["Ein Topf", "Vegan"],
    publishedAt: "2026-05-19",
    popularity: 79,
  },
  {
    slug: "kaesespaetzle",
    title: "Käsespätzle mit Röstzwiebeln",
    category: "herzhaft",
    excerpt:
      "Spätzleteig selbst gemacht, mit drei Käsesorten geschichtet. Sonntagsessen mit Aufwand-Rechtfertigung.",
    image: "https://placehold.co/800x600/4F7C4A/FFFFFF?text=K%C3%A4sesp%C3%A4tzle",
    videoUrl: "",
    videoPlatform: "youtube",
    prepTimeMinutes: 60,
    difficulty: "mittel",
    servings: 4,
    ingredients: [
      { amount: "400 g", name: "Spätzlemehl (oder Type 405)" },
      { amount: "4", name: "Eier" },
      { amount: "200 ml", name: "Wasser mit Kohlensäure" },
      { amount: "1 TL", name: "Salz" },
      { amount: "1 Prise", name: "Muskatnuss" },
      { amount: "150 g", name: "Bergkäse" },
      { amount: "100 g", name: "Emmentaler" },
      { amount: "50 g", name: "Räucherkäse" },
      { amount: "3", name: "Zwiebeln" },
      { amount: "40 g", name: "Butter" },
    ],
    steps: [
      "Mehl, Eier, Salz, Muskat und Wasser zu einem zähen Teig schlagen, bis er Blasen wirft. 15 Minuten ruhen lassen.",
      "Zwiebeln in feine Ringe schneiden und in der Butter bei mittlerer Hitze 15 Minuten goldbraun rösten. Geduld – bei zu großer Hitze werden sie bitter.",
      "Reichlich Salzwasser aufkochen. Teig portionsweise durch Spätzlehobel oder vom Brett ins Wasser schaben.",
      "Spätzle abschöpfen, sobald sie oben schwimmen, und kurz kalt abschrecken.",
      "Käse mischen. Spätzle und Käse abwechselnd in einer Auflaufform schichten, oben Käse.",
      "Bei 200 °C 15 Minuten überbacken, bis der Käse Blasen wirft.",
      "Mit den Röstzwiebeln bestreuen und sofort servieren.",
    ],
    linkedProductSlugs: ["linen-apron", "weeknight-pdf"],
    tags: ["Soulfood", "Sonntag"],
    publishedAt: "2026-04-30",
    popularity: 87,
  },
];

export function getRecipe(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}

export function getRecipes(slugs: string[]): Recipe[] {
  return slugs
    .map((slug) => getRecipe(slug))
    .filter((r): r is Recipe => Boolean(r));
}

export const recipesByDate = [...recipes].sort((a, b) =>
  b.publishedAt.localeCompare(a.publishedAt)
);

export const recipesByPopularity = [...recipes].sort(
  (a, b) => b.popularity - a.popularity
);

export function formatTime(minutes: number): string {
  if (minutes < 60) return `${minutes} min`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m === 0 ? `${h} h` : `${h} h ${m} min`;
}

/**
 * The recipe data keeps its German difficulty keys – these are the labels
 * shown in the (English) interface.
 */
export const difficultyLabel: Record<Difficulty, string> = {
  einfach: "Easy",
  mittel: "Medium",
  anspruchsvoll: "Advanced",
};
